os: osx
osx_image: xcode9.3
language: cpp
script:
  - xcodebuild -project polyroot/polyroot.xcodeproj -scheme polyroot
  - xcodebuild -project finiteDifferences/finiteDifferences.xcodeproj -scheme finiteDifferences
