.TH "src/bbpTypeFormula.cpp" 3 "Tue Jan 22 2019" "Cpp Examples" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/bbpTypeFormula.cpp \- BPP Type formula calculation\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'bbpTypeFormula\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "long double \fBP\fP (const int &s, const int &b, const int &n, const std::vector< int > &A, const int &n_iter)"
.br
.RI "BPP Type formula calculation\&. "
.in -1c
.SH "Detailed Description"
.PP 
BPP Type formula calculation\&. 

The Bailey–Borwein–Plouffe formula (BBP formula) is a spigot algorithm which is an algorithm for computing the value of a mathematical constant such as π or e which generates output digits in some base (usually 2 or a power of 2) from left to right, with limited intermediate storage\&. The name comes from the sense of the word 'spigot' for a tap or valve controlling the flow of a liquid\&.
.PP
Formula was taken from: https://bbp.carma.newcastle.edu.au/
.PP
\fBAuthor:\fP
.RS 4
Murat Koptur mkoptur3@gmail.com
.RE
.PP
Last updated: 22/Jan/2019\&. 
.SH "Function Documentation"
.PP 
.SS "long double P (const int & s, const int & b, const int & n, const std::vector< int > & A, const int & n_iter)"

.PP
BPP Type formula calculation\&. 
.PP
\fBParameters:\fP
.RS 4
\fIs\fP An integer\&. 
.br
\fIb\fP An integer\&. 
.br
\fIn\fP An integer\&. 
.br
\fIA\fP A sequence of integers\&. 
.br
\fIn_iter\fP Iteration count\&.
.RE
.PP
\fBReturns:\fP
.RS 4
Approximation of a number\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Cpp Examples from the source code\&.
