.TH "src/binom.h" 3 "Tue Jan 22 2019" "Cpp Examples" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/binom.h \- Calculate binomial coefficient\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBbinomCoef\fP (const unsigned long &n, const unsigned long &k)"
.br
.RI "Calculate binomial coefficient\&. "
.in -1c
.SH "Detailed Description"
.PP 
Calculate binomial coefficient\&. 


.PP
\fBAuthor:\fP
.RS 4
Murat Koptur mkoptur3@gmail.com
.RE
.PP
Last updated: 22/Jan/2019\&. 
.SH "Function Documentation"
.PP 
.SS "double binomCoef (const unsigned long & n, const unsigned long & k)"

.PP
Calculate binomial coefficient\&. 
.PP
\fBParameters:\fP
.RS 4
\fIn\fP An integer\&. 
.br
\fIk\fP An integer\&.
.RE
.PP
\fBReturns:\fP
.RS 4
Binomial coefficient\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Cpp Examples from the source code\&.
