.TH "src/brentSalaminFormula.h" 3 "Sun Oct 13 2019" "Cpp Examples" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/brentSalaminFormula.h \- Brent-Salamin Formula\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <cmath>\fP
.br
\fC#include <vector>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T  = long double> T \fBcalc_pi\fP (const unsigned int &n_iter)"
.br
.RI "Brent-Salamin Formula\&. "
.in -1c
.SH "Detailed Description"
.PP 
Brent-Salamin Formula\&. 

The Brent-Salamin formula, also called the Gauss-Salamin formula or Salamin formula, is a formula that uses the arithmetic-geometric mean to compute pi\&.
.PP
\fBAuthor:\fP
.RS 4
Murat Koptur mkoptur3@gmail.com
.RE
.PP
Last updated: 24/Jan/2019\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename T  = long double> T calc_pi (const unsigned int & n_iter)"

.PP
Brent-Salamin Formula\&. 
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP Type of return value\&. Choose appropriate type for precision which you want\&. 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIn_iter\fP Iteration count\&.
.RE
.PP
\fBReturns:\fP
.RS 4
Approximation of pi\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Cpp Examples from the source code\&.
