.TH "Data< T >" 3 "Sun Oct 13 2019" "Cpp Examples" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Data< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lagrangeInterpolation\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBData\fP (std::vector< T > x, std::vector< T > y)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< T > \fBx\fP"
.br
.ti -1c
.RI "std::vector< T > \fBy\fP"
.br
.ti -1c
.RI "unsigned long \fBsize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T = long double>
.br
struct Data< T >"
A struct for storing x and y values\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Cpp Examples from the source code\&.
