.TH "Dual" 3 "Sun Oct 13 2019" "Cpp Examples" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dual
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDual\fP (const long double &a)"
.br
.ti -1c
.RI "\fBDual\fP (const long double &a, const long double &b)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long double \fBreal\fP"
.br
.ti -1c
.RI "long double \fBdual\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Cpp Examples from the source code\&.
