.TH "src/goldenSectionSearch.h" 3 "Tue Jan 22 2019" "Cpp Examples" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/goldenSectionSearch.h \- Golden Section Search\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <cassert>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <functional>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBResult\fP"
.br
.RI "The struct that stores result\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBResult\fP \fBGoldenSectionSearch\fP (double a, double b, const double &tol, const std::function< double(double)> &func)"
.br
.RI "Golden Section Search\&. "
.in -1c
.SH "Detailed Description"
.PP 
Golden Section Search\&. 

The golden-section search is a technique for finding the extremum (minimum or maximum) of a strictly unimodal function by successively narrowing the range of values inside which the extremum is known to exist\&. The technique derives its name from the fact that the algorithm maintains the function values for triples of points whose distances form a golden ratio\&.
.PP
\fBAuthor:\fP
.RS 4
Murat Koptur mkoptur3@gmail.com
.RE
.PP
Last updated: 22/Jan/2019\&. 
.SH "Function Documentation"
.PP 
.SS "\fBResult\fP GoldenSectionSearch (double a, double b, const double & tol, const std::function< double(double)> & func)"

.PP
Golden Section Search\&. 
.PP
\fBParameters:\fP
.RS 4
\fIa\fP Lower bound\&. 
.br
\fIb\fP Upper bound\&. 
.br
\fItol\fP Tolerance\&. 
.br
\fIfunc\fP The function\&.
.RE
.PP
\fBReturns:\fP
.RS 4
The interval with d-c<=tol\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Cpp Examples from the source code\&.
