.TH "src/lcg.cpp" 3 "Tue Jan 22 2019" "Cpp Examples" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/lcg.cpp \- Linear Congruential Generator\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'lcg\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "std::vector< int > \fBlcg\fP (const int &seed, const int &mod, const int &mult, const int &incr, const int &count)"
.br
.RI "Linear Congruential Generator\&. "
.in -1c
.SH "Detailed Description"
.PP 
Linear Congruential Generator\&. 

Linear Congruential Generator is an algorithm that yields a sequence of pseudo–randomized numbers calculated with a discontinuous piecewise linear equation\&. The method represents one of the oldest and best–known pseudorandom number generator algorithms\&.
.PP
\fBAuthor:\fP
.RS 4
Murat Koptur mkoptur3@gmail.com
.RE
.PP
Last updated: 22/Jan/2019\&. 
.SH "Function Documentation"
.PP 
.SS "std::vector<int> lcg (const int & seed, const int & mod, const int & mult, const int & incr, const int & count)"

.PP
Linear Congruential Generator\&. 
.PP
\fBParameters:\fP
.RS 4
\fIseed\fP Seed\&. 
.br
\fImod\fP Modulus\&. 
.br
\fImult\fP Multiplier\&. 
.br
\fIincr\fP Increment\&. 
.br
\fIcount\fP Count of generated numbers\&.
.RE
.PP
\fBReturns:\fP
.RS 4
Vector of generated numbers\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Cpp Examples from the source code\&.
