.TH "src/polyroot.h" 3 "Tue Jan 22 2019" "Cpp Examples" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/polyroot.h \- Quadratic formula\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "std::vector< double > \fBpolyroot\fP (const std::vector< double > &coef)"
.br
.RI "Quadratic formula\&. "
.in -1c
.SH "Detailed Description"
.PP 
Quadratic formula\&. 

Quadratic Formula is the solution of the quadratic equation\&.
.PP
\fBAuthor:\fP
.RS 4
Murat Koptur mkoptur3@gmail.com
.RE
.PP
Last updated: 22/Jan/2019\&. 
.SH "Function Documentation"
.PP 
.SS "std::vector<double> polyroot (const std::vector< double > & coef)"

.PP
Quadratic formula\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcoef\fP Coefficient vector\&.
.RE
.PP
\fBReturns:\fP
.RS 4
Roots of quadratic equation\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Cpp Examples from the source code\&.
