.TH "src/rungeKutta.h" 3 "Tue Jan 22 2019" "Cpp Examples" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rungeKutta.h \- Runge-Kutta Order Four\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <functional>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBRK4\fP (const double &a, const double &b, const unsigned int &N, const double &init, const std::function< double(double, double)> &func)"
.br
.RI "Runge-Kutta Order Four\&. "
.in -1c
.SH "Detailed Description"
.PP 
Runge-Kutta Order Four\&. 

Runge-Kutta methods are a family of implicit and explicit iterative methods, which include the well-known routine called the Euler Method, used in temporal discretization for the approximate solutions of ordinary differential equations\&.
.PP
\fBAuthor:\fP
.RS 4
Murat Koptur mkoptur3@gmail.com
.RE
.PP
Last updated: 22/Jan/2019\&. 
.SH "Function Documentation"
.PP 
.SS "double RK4 (const double & a, const double & b, const unsigned int & N, const double & init, const std::function< double(double, double)> & func)"

.PP
Runge-Kutta Order Four\&. 
.PP
\fBParameters:\fP
.RS 4
\fIa\fP Endpoint\&. 
.br
\fIb\fP Endpoint\&. 
.br
\fIN\fP Iteration count\&. 
.br
\fIinit\fP Initial condition\&. 
.br
\fIfunc\fP A function\&.
.RE
.PP
\fBReturns:\fP
.RS 4
Approximation to exact solution\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Cpp Examples from the source code\&.
